---

services:
  backend:
    container_name: fng-backend
    image: nikogenia/fng-backend:latest
    restart: unless-stopped
    networks:
      - fng
  frontend:
    container_name: fng-frontend
    image: nikogenia/fng-frontend:latest
    restart: unless-stopped
    networks:
      - fng
  redis:
    container_name: fng-redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - fng

networks:
  fng:
    external: true
